version: "3.7"

services:

  go:
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: classicmodels
      DB_USER: dev
      DB_PASSWORD: dev
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - 1323:80

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - db-data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306

volumes:
  db-data: